#!/usr/bin/env python

import argparse
import json
import os.path

from pds.aossrequestsigner.run import run as run_aoss_request_signer
from pds.aossrequestsigner.utils import get_checked_filepath, parse_path, process_data_arg


def parse_args() -> argparse.Namespace:
    args = argparse.ArgumentParser()

    verbosity_group = args.add_mutually_exclusive_group()
    verbosity_group.add_argument('-v', '--verbose', action='store_true', help='Provide verbose stdout output')
    verbosity_group.add_argument('-s', '--silent', action='store_true', help='Suppress stdout output')

    args.add_argument('path', type=parse_path,
                      help='either a full URL (<scheme>://<host>/<path>) or a host-relative path (/<path>) for the request. Providing a full URL will not override the host endpoint provided as an environment variable (this may change in future)')
    args.add_argument('-d', '--data', type=process_data_arg, default={'query': {'match_all': {}}},
                      help='POST body to include in the request. Defaults to an OpenSearch match-all query.  See https://opensearch.org/docs/latest/query-dsl/ for details.')
    args.add_argument('-o', '--output', dest='output_filepath', type=get_checked_filepath, default=None,
                      help='Output filepath for response content')
    args.add_argument('-H', '--header', dest='headers', default=[], action='append', nargs='*',
                      help='Add an extra header to use in the request, in format "Key: Value". "Content-Type: application/json" is included by default but may be overwritten.')

    args.add_argument('-p', '--pretty', action='store_true', help='Prettify output with a 2-space-indent JSON format')

    return args.parse_args()


if __name__ == '__main__':
    cognito_user = os.environ['REQUEST_SIGNER_COGNITO_USER']
    cognito_password = os.environ['REQUEST_SIGNER_COGNITO_PASSWORD']

    aws_account_id = os.environ['REQUEST_SIGNER_AWS_ACCOUNT']
    aws_region = os.environ.get('AWS_REGION', 'us-west-2')
    client_id = os.environ['REQUEST_SIGNER_CLIENT_ID']
    user_pool_id = os.environ['REQUEST_SIGNER_USER_POOL_ID']
    identity_pool_id = os.environ['REQUEST_SIGNER_IDENTITY_POOL_ID']

    aoss_endpoint = os.environ['REQUEST_SIGNER_AOSS_ENDPOINT']

    args = parse_args()

    run_aoss_request_signer(
        aws_region,
        aws_account_id,
        client_id,
        identity_pool_id,
        user_pool_id,
        cognito_user,
        cognito_password,
        aoss_endpoint,
        args.path,
        data=args.data,
        additional_headers=args.headers,
        output_filepath=args.output_filepath,
        verbose=args.verbose,
        silent=args.silent,
        prettify_output=args.pretty,
    )